version: "3"
services:
  jupyter:
    image: davealonbehr/heuristics-notebook
    ports:
      - 8888:8888
    volumes:
      - ${PWD}:/home/jovyan/work
    links:
      - postgres
    command: start-notebook.sh --NotebookApp.token=''
  postgres:
    image: postgres:11.6
    expose:
      - "5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: --data-checksums
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
